#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs/
# ------------------------------------------------------------------------------

# Note: A full config spec is located at ./vector.spec.toml and examples
#       in the ./examples folder.

data_dir = "/var/lib/vector"

# Input data. Change me to a valid input source.
[sources.stdin]
  type = "stdin"

[sources.socket]
  type = "socket"
  mode = "tcp"
  address = "0.0.0.0:9000"

# Transform data
[transforms.json]
  type = "json_parser"
  inputs = ["socket"]
  drop_invalid = true
  field = "message"

# Output data
[sinks.console]
  type     = "console"
  inputs   = ["stdin", "json"]
  encoding = "text"

[sinks.elasticsearch]
  type        = "elasticsearch"
  inputs      = ["json"]
  healthcheck = true
  endpoint    = "http://elasticsearch:9200"
  bulk.action = "create"
  bulk.index  = "linode-account-events-%F"

[sinks.slack]
  type        = "http"
  inputs      = ["json"]
  healthcheck = true
  uri         = "http://sink:3000/sink-slack"
  encoding    = "json"
