version: "3.7"
services:

  ingest:
    build:
      context: ./ingest
    environment:
      - LINODE_TOKEN
    volumes:
      - ./ingest:/app
      - ./ingest/config:/etc/ingest
      - ingest-data:/var/lib/ingest/data
    networks:
      - backend

  vector:
    image: timberio/vector:0.8.X-alpine
    volumes:
      - ./vector/config:/etc/vector
    networks:
      - elastic
      - backend
    depends_on:
      - elasticsearch

#  delivery:
#    build:
#      context: ./delivery
#    volumes:
#      - ./delivery/config:/etc/delivery
#      - delivery-data:/var/lib/delivery/data
#    networks:
#      - backend
#
#  dashboard:
#    build:
#      context: ./dashboard
#    volumes:
#      - ./dashboard/config:/etc/dashboard
#    networks:
#      - backend
#      - frontend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch

networks:
  frontend:
  backend:
  elastic:
    driver: bridge

volumes:
  ingest-data:
  delivery-data:
  es-data:
    driver: local
