version: "3.7"
services:

  source:
    build:
      context: .
      dockerfile: build/package/Dockerfile-linode-event-source
    environment:
      - LINODE_TOKEN
    volumes:
      - ./config/source.toml:/etc/source/source.toml
    networks:
      - backend

  vector:
    image: timberio/vector:latest-alpine
    volumes:
      - ./config/vector.toml:/etc/vector/vector.toml
    networks:
      - backend

  sink:
    build:
      context: .
      dockerfile: build/package/Dockerfile-linode-event-sink-slack
    volumes:
      - ./config/sink.toml:/etc/sink/sink.toml
    networks:
      - backend

networks:
  backend:
