version: "3.7"
services:

  source:
    build:
      context: .
      dockerfile: build/package/Dockerfile-linode-event-source
    environment:
      - LINODE_TOKEN
    volumes:
      - ${LED_CONFIG_DIR:-./config}/source.toml:/etc/source/source.toml
    networks:
      - backend

  vector:
    image: timberio/vector:latest-alpine
    volumes:
      - ${LED_CONFIG_DIR:-./config}/vector.toml:/etc/vector/vector.toml
    networks:
      - elastic
      - backend
    depends_on:
      - elasticsearch

  sink:
    build:
      context: .
      dockerfile: build/package/Dockerfile-linode-event-sink-slack
    volumes:
      - ${LED_CONFIG_DIR:-./config}/sink.toml:/etc/sink/sink.toml
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    ports:
      - 127.0.0.1:5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch

networks:
  backend:
  elastic:

volumes:
  es-data:
    driver: local
